// shared/src/achievements.ts

export type AchievementRarity = 'common' | 'rare' | 'epic' | 'legendary';

export type AchievementCategory =
  | 'beginner'
  | 'academic'
  | 'wealth'
  | 'explorer'
  | 'cards'
  | 'plans'
  | 'survival'
  | 'social'
  | 'food'
  | 'composite'
  | 'hidden';

export interface AchievementDef {
  id: string;
  name: string;
  description: string;
  revealedDescription?: string;
  category: AchievementCategory;
  rarity: AchievementRarity;
  points: number;
  hidden: boolean;
  icon: string;
  maxProgress?: number;
  progressLabel?: string;
}

export interface PlayerAchievement {
  achievementId: string;
  unlockedAt: string;
  gameId?: string;
}

export interface AchievementProgress {
  achievementId: string;
  current: number;
  max: number;
}

export interface PlayerAchievementSummary {
  unlocked: PlayerAchievement[];
  progress: AchievementProgress[];
  totalPoints: number;
  rank: string;
  rankIcon: string;
}

export interface GameSessionStats {
  lowestMoney: number;
  diceRolls: number[];
  cardsDrawn: string[];
  defenseCardsUsed: number;
  maxHandSize: number;
  turnsSkipped: number;
  dingPenalties: number;
  waitingRoomTeleports: number;
  nannaCPGifts: number;
  votesMajoritySide: number;
  chanceCardsTargetedBy: number;
  offensiveCardsUsed: number;
  chainCardParticipated: boolean;
  chainCardPositive: boolean;
  usedDelayedGratification: boolean;
  usedPlanSwap: boolean;
  samePlanOpponentWin: boolean;
  compositeScoreAtYear1End: number;
  wasLowestAtYear3End: boolean;
  consecutiveLowDice: number;
  consecutiveHighDice: number;
  maxConsecutiveLowDice: number;    // peak consecutive low dice (<=2) during the game
  maxConsecutiveHighDice: number;   // peak consecutive high dice (>=5) during the game
  wasHighestAtYear1End: boolean;    // was this player's composite score highest at year 1 end
  emptyHandThenDrew: boolean;       // drew a card immediately after hand was emptied (card_05)
  reverseOrderBenefit: boolean;
  startPassCount: number;
  foodLineAllPositive: boolean;
  othersWentBankrupt: boolean;
  cafeteriaNoNegativeStreak: number;
  foodLineCompleted: boolean;
  usedMaimenShield: boolean;
  hospitalVisits: number;
  hospitalEscapes: number;           // times escaped hospital (dice or pay)
  redistributionCardsUsed: number;   // times used 劫富济贫
  stealCardsUsed: number;            // times used 朋辈导师 to steal
  totalTuitionPaid: number;
  linesVisited: string[];
  allPositiveChanceCards: boolean;
  consecutiveRedraws: number;
  maxDefenseChainLength: number;  // max negate cards chained in a single event
}

// ─── Rank / Tier System ──────────────────────────────────────────────────────

export interface RankDef {
  minPoints: number;
  icon: string;
  name: string;
  title: string;
}

export const RANKS: RankDef[] = [
  { minPoints: 0, icon: '🥚', name: '萌新', title: '菜根新芽' },
  { minPoints: 50, icon: '🌱', name: '入门', title: '初窥门径' },
  { minPoints: 150, icon: '🌿', name: '进阶', title: '学有所成' },
  { minPoints: 350, icon: '🌳', name: '精通', title: '游刃有余' },
  { minPoints: 650, icon: '🏆', name: '大师', title: '南哪通' },
  { minPoints: 1000, icon: '👑', name: '传说', title: '菜根人生家' },
];

export function getRank(points: number): RankDef {
  let result = RANKS[0];
  for (const rank of RANKS) {
    if (points >= rank.minPoints) {
      result = rank;
    }
  }
  return result;
}

// ─── Achievement Definitions ─────────────────────────────────────────────────

export const ACHIEVEMENTS: AchievementDef[] = [
  // ── Chapter 1: Beginner (8) ─────────────────────────────────────────────
  {
    id: 'new_01',
    name: '报到!',
    description: '完成第一局游戏',
    category: 'beginner',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🎓',
    maxProgress: 1,
    progressLabel: '已完成 {n}/{max} 局',
  },
  {
    id: 'new_02',
    name: '初尝胜果',
    description: '赢得第一场胜利',
    category: 'beginner',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🎓',
    maxProgress: 1,
    progressLabel: '已赢得 {n}/{max} 场',
  },
  {
    id: 'new_03',
    name: '常驻玩家',
    description: '累积完成 10 局游戏',
    category: 'beginner',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🎓',
    maxProgress: 10,
    progressLabel: '已完成 {n}/{max} 局',
  },
  {
    id: 'new_04',
    name: '身经百战',
    description: '累积完成 50 局游戏',
    category: 'beginner',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🎓',
    maxProgress: 50,
    progressLabel: '已完成 {n}/{max} 局',
  },
  {
    id: 'new_05',
    name: '南哪老炮儿',
    description: '累积完成 100 局游戏',
    category: 'beginner',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🎓',
    maxProgress: 100,
    progressLabel: '已完成 {n}/{max} 局',
  },
  {
    id: 'new_06',
    name: '三连胜',
    description: '连续赢得 3 场游戏',
    category: 'beginner',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🎓',
    maxProgress: 3,
    progressLabel: '已连胜 {n}/{max} 场',
  },
  {
    id: 'new_07',
    name: '五连胜',
    description: '连续赢得 5 场游戏',
    category: 'beginner',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🎓',
    maxProgress: 5,
    progressLabel: '已连胜 {n}/{max} 场',
  },
  {
    id: 'new_08',
    name: '满员开战',
    description: '在 6 人满员局中完成一局',
    category: 'beginner',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🎓',
  },

  // ── Chapter 2: Academic (8) ──────────────────────────────────────────────
  {
    id: 'gpa_01',
    name: '及格万岁',
    description: '单局结束时 GPA ≥ 2.0',
    category: 'academic',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '📚',
  },
  {
    id: 'gpa_02',
    name: '优秀毕业生',
    description: '单局结束时 GPA ≥ 3.5',
    category: 'academic',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '📚',
  },
  {
    id: 'gpa_03',
    name: '学神降临',
    description: '单局结束时 GPA ≥ 4.0',
    category: 'academic',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '📚',
  },
  {
    id: 'gpa_04',
    name: '满绩传说',
    description: '单局结束时 GPA ≥ 4.5',
    category: 'academic',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '📚',
  },
  {
    id: 'gpa_05',
    name: 'GPA 突破天际',
    description: '单局结束时 GPA ≥ 5.0',
    category: 'academic',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '📚',
  },
  {
    id: 'gpa_06',
    name: '累积学分',
    description: '历史最高 GPA ≥ 4.0',
    category: 'academic',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '📚',
  },
  {
    id: 'gpa_07',
    name: '稳定发挥',
    description: '连续 5 局结束 GPA ≥ 3.0',
    category: 'academic',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '📚',
    maxProgress: 5,
    progressLabel: '已连续 {n}/{max} 局',
  },
  {
    id: 'gpa_08',
    name: '绩点收割机',
    description: '累积所有局的 GPA 总和 ≥ 50',
    category: 'academic',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '📚',
    maxProgress: 50,
    progressLabel: '累积 GPA {n}/{max}',
  },

  // ── Chapter 3: Wealth (10) ───────────────────────────────────────────────
  {
    id: 'money_01',
    name: '小有积蓄',
    description: '单局结束时金钱 ≥ 3500',
    category: 'wealth',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '💰',
  },
  {
    id: 'money_02',
    name: '精打细算',
    description: '单局结束时金钱 ≥ 4500',
    category: 'wealth',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💰',
  },
  {
    id: 'money_03',
    name: '校园富豪',
    description: '单局结束时金钱 ≥ 5555',
    category: 'wealth',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '💰',
  },
  {
    id: 'money_04',
    name: '富可敌校',
    description: '单局结束时金钱 ≥ 7000',
    category: 'wealth',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '💰',
  },
  {
    id: 'money_05',
    name: '破产警告',
    description: '单局中金钱曾跌破 500',
    category: 'wealth',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '💰',
  },
  {
    id: 'money_06',
    name: '绝处逢生',
    description: '单局金钱曾跌破 500 后最终 ≥ 3000',
    category: 'wealth',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '💰',
  },
  {
    id: 'money_07',
    name: '过路财神',
    description: '累积经过起点领取工资 ≥ 10 次',
    category: 'wealth',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💰',
    maxProgress: 10,
    progressLabel: '已经过起点 {n}/{max} 次',
  },
  {
    id: 'money_08',
    name: '散财童子',
    description: '单局在南哪诚品给其他玩家发钱 2 次以上',
    category: 'wealth',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💰',
  },
  {
    id: 'money_09',
    name: '学费大户',
    description: '单局累积交学费 ≥ 800',
    category: 'wealth',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💰',
  },
  {
    id: 'money_10',
    name: '累积万金',
    description: '历史所有局累积金钱总和 ≥ 50000',
    category: 'wealth',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '💰',
    maxProgress: 50000,
    progressLabel: '累积金钱 {n}/{max}',
  },

  // ── Chapter 4: Explorer (14) ─────────────────────────────────────────────
  {
    id: 'explore_01',
    name: '初出茅庐',
    description: '单局探索值 ≥ 5',
    category: 'explorer',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🗺️',
  },
  {
    id: 'explore_02',
    name: '见多识广',
    description: '单局探索值 ≥ 15',
    category: 'explorer',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🗺️',
  },
  {
    id: 'explore_03',
    name: '世界那么大',
    description: '单局探索值 ≥ 25',
    category: 'explorer',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🗺️',
  },
  {
    id: 'explore_04',
    name: '探索之王',
    description: '单局探索值 ≥ 30',
    category: 'explorer',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '🗺️',
  },
  {
    id: 'line_01',
    name: '尝鲜一条线',
    description: '单局进入任意 1 条支线',
    category: 'explorer',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🗺️',
  },
  {
    id: 'line_02',
    name: '三线并进',
    description: '单局进入 3 条不同支线',
    category: 'explorer',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🗺️',
  },
  {
    id: 'line_03',
    name: '五线谱',
    description: '单局进入 5 条不同支线',
    category: 'explorer',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🗺️',
  },
  {
    id: 'line_04',
    name: '全线通关',
    description: '单局进入全部 8 条支线',
    category: 'explorer',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '🗺️',
  },
  {
    id: 'line_05',
    name: '浦口老兵',
    description: '累积进入浦口线 ≥ 10 次',
    category: 'explorer',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🗺️',
    maxProgress: 10,
    progressLabel: '已进入浦口线 {n}/{max} 次',
  },
  {
    id: 'line_06',
    name: '食堂常客',
    description: '累积进入食在南哪线 ≥ 10 次',
    category: 'explorer',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🗺️',
    maxProgress: 10,
    progressLabel: '已进入食堂线 {n}/{max} 次',
  },
  {
    id: 'line_07',
    name: '鼓楼情怀',
    description: '累积进入鼓楼线 ≥ 10 次',
    category: 'explorer',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🗺️',
    maxProgress: 10,
    progressLabel: '已进入鼓楼线 {n}/{max} 次',
  },
  {
    id: 'line_08',
    name: '支线收藏家',
    description: '历史累积进入过全部 8 条支线',
    category: 'explorer',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🗺️',
    maxProgress: 8,
    progressLabel: '已解锁支线 {n}/{max} 条',
  },
  {
    id: 'line_09',
    name: '仙林一日游',
    description: '单局在仙林线内完成全部格子',
    category: 'explorer',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🗺️',
  },
  {
    id: 'line_10',
    name: '四校区集齐',
    description: '单局访问浦口、鼓楼、仙林、苏州四条校区线',
    category: 'explorer',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🗺️',
  },

  // ── Chapter 5: Cards (10) ────────────────────────────────────────────────
  {
    id: 'card_01',
    name: '抽卡入门',
    description: '累积抽取 10 张卡牌',
    category: 'cards',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🃏',
    maxProgress: 10,
    progressLabel: '已抽取 {n}/{max} 张',
  },
  {
    id: 'card_02',
    name: '卡牌收藏家',
    description: '累积抽取 100 张卡牌',
    category: 'cards',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🃏',
    maxProgress: 100,
    progressLabel: '已抽取 {n}/{max} 张',
  },
  {
    id: 'card_03',
    name: '及时止损大师',
    description: '累积使用防御卡 ≥ 10 次',
    category: 'cards',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🃏',
    maxProgress: 10,
    progressLabel: '已使用防御卡 {n}/{max} 次',
  },
  {
    id: 'card_04',
    name: '手握王牌',
    description: '单局同时持有 4 张及以上手牌',
    category: 'cards',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🃏',
  },
  {
    id: 'card_05',
    name: '空城计',
    description: '单局中所有手牌用完后立即再抽到牌',
    category: 'cards',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🃏',
  },
  {
    id: 'card_06',
    name: '连锁反应',
    description: '单局中一次事件触发 2 张以上防御卡连锁',
    category: 'cards',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🃏',
  },
  {
    id: 'card_07',
    name: '骰子达人',
    description: '累积投出 6 点 ≥ 20 次',
    category: 'cards',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🃏',
    maxProgress: 20,
    progressLabel: '已投出 6 点 {n}/{max} 次',
  },
  {
    id: 'card_08',
    name: '蛇眼',
    description: '单局中投出 1 点 3 次以上',
    category: 'cards',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🃏',
  },
  {
    id: 'card_09',
    name: '命运之子',
    description: '单局中抽到的命运卡全部为正面效果',
    category: 'cards',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🃏',
  },
  {
    id: 'card_10',
    name: '欧皇附体',
    description: '单局连续 3 次投出 5 或 6',
    category: 'cards',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🃏',
  },

  // ── Chapter 6: Plans (12) ────────────────────────────────────────────────
  {
    id: 'plan_01',
    name: '选定方向',
    description: '第一次使用培养计划获胜',
    category: 'plans',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🎓',
  },
  {
    id: 'plan_02',
    name: '双学位',
    description: '单局中拥有 2 个培养计划并获胜',
    category: 'plans',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🎓',
  },
  {
    id: 'plan_03',
    name: '三修战士',
    description: '单局拥有 3 个培养计划',
    category: 'plans',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🎓',
  },
  {
    id: 'plan_04',
    name: '文理兼修',
    description: '使用过文科计划和理科计划各获胜一次',
    category: 'plans',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🎓',
  },
  {
    id: 'plan_05',
    name: '法学精英',
    description: '使用法学院获胜',
    category: 'plans',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🎓',
  },
  {
    id: 'plan_06',
    name: '医者仁心',
    description: '使用医学院获胜',
    category: 'plans',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🎓',
  },
  {
    id: 'plan_07',
    name: '代码之神',
    description: '使用计算机系获胜',
    category: 'plans',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '🎓',
  },
  {
    id: 'plan_08',
    name: '仰望星空',
    description: '使用天文学院获胜',
    category: 'plans',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🎓',
  },
  {
    id: 'plan_09',
    name: '计划通',
    description: '累积使用 10 种不同的培养计划',
    category: 'plans',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🎓',
    maxProgress: 10,
    progressLabel: '已使用 {n}/{max} 种计划',
  },
  {
    id: 'plan_10',
    name: '百科全书',
    description: '累积使用过全部 32 种培养计划',
    category: 'plans',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '🎓',
    maxProgress: 32,
    progressLabel: '已解锁 {n}/{max} 种计划',
  },
  {
    id: 'plan_11',
    name: '跨院达人',
    description: '单局中使用跨院准出卡交换过专业',
    category: 'plans',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🎓',
  },
  {
    id: 'plan_12',
    name: '同院校友',
    description: '与另一玩家使用相同培养计划且你获胜',
    category: 'plans',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🎓',
  },

  // ── Chapter 7: Survival (14) ─────────────────────────────────────────────
  {
    id: 'surv_01',
    name: '住院达人',
    description: '单局进入校医院 ≥ 3 次',
    category: 'survival',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_02',
    name: '铁头功',
    description: '单局在鼎被罚 ≥ 2 次',
    category: 'survival',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_03',
    name: '起死回生',
    description: '单局金钱曾跌破 500 后最终获胜',
    category: 'survival',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_04',
    name: '绝地翻盘',
    description: '单局大三结束时综合分最低，最终获胜',
    category: 'survival',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_05',
    name: '越挫越勇',
    description: '连续 3 局未获胜后获胜',
    category: 'survival',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_06',
    name: '交不起学费',
    description: '单局在学费格被扣 ≥ 500 金',
    category: 'survival',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_07',
    name: '医院逃跑王',
    description: '累积从医院逃脱 ≥ 10 次',
    category: 'survival',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💪',
    maxProgress: 10,
    progressLabel: '已逃脱 {n}/{max} 次',
  },
  {
    id: 'surv_08',
    name: '命悬一线',
    description: '单局中金钱曾跌到 100 以下但最终未破产',
    category: 'survival',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_09',
    name: '见证破产',
    description: '在一局中目睹其他玩家破产',
    category: 'survival',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_10',
    name: '全勤奖',
    description: '单局完成全部 24 回合未跳过任何一回合',
    category: 'survival',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_11',
    name: '初次破产',
    description: '第一次在游戏中破产',
    category: 'survival',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '💪',
  },
  {
    id: 'surv_12',
    name: '破产专业户',
    description: '累积破产 5 次',
    category: 'survival',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '💪',
    maxProgress: 5,
    progressLabel: '已破产 {n}/{max} 次',
  },
  {
    id: 'surv_13',
    name: '屡败屡战',
    description: '累积破产 10 次但仍在游戏',
    category: 'survival',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '💪',
    maxProgress: 10,
    progressLabel: '已破产 {n}/{max} 次',
  },
  {
    id: 'surv_14',
    name: '浴火重生',
    description: '上一局破产，下一局获胜',
    category: 'survival',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '💪',
  },

  // ── Chapter 8: Social (8) ────────────────────────────────────────────────
  {
    id: 'social_01',
    name: '投票先锋',
    description: '累积参与投票事件 ≥ 10 次',
    category: 'social',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '👥',
    maxProgress: 10,
    progressLabel: '已参与投票 {n}/{max} 次',
  },
  {
    id: 'social_02',
    name: '意见领袖',
    description: '单局中在投票事件中 3 次站在多数方',
    category: 'social',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '👥',
  },
  {
    id: 'social_03',
    name: '劫富济贫',
    description: '累积使用再分配卡 ≥ 5 次',
    category: 'social',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '👥',
    maxProgress: 5,
    progressLabel: '已使用再分配卡 {n}/{max} 次',
  },
  {
    id: 'social_04',
    name: '朋辈导师',
    description: '累积使用朋辈导师卡偷牌 ≥ 5 次',
    category: 'social',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '👥',
    maxProgress: 5,
    progressLabel: '已使用朋辈导师卡 {n}/{max} 次',
  },
  {
    id: 'social_05',
    name: '众矢之的',
    description: '单局中被其他玩家使用机会卡针对 ≥ 5 次',
    category: 'social',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '👥',
  },
  {
    id: 'social_06',
    name: '和平主义者',
    description: '单局中从未使用针对性机会卡',
    category: 'social',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '👥',
  },
  {
    id: 'social_07',
    name: '八卦传播者',
    description: '在八卦秘闻连锁事件中选择参与并获得正面结果',
    category: 'social',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '👥',
  },
  {
    id: 'social_08',
    name: '与人为善',
    description: '累积与 20 个不同玩家一起游玩',
    category: 'social',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '👥',
    maxProgress: 20,
    progressLabel: '已与 {n}/{max} 位不同玩家游玩',
  },

  // ── Chapter 9: Food (6) ──────────────────────────────────────────────────
  {
    id: 'food_01',
    name: '食堂新人',
    description: '第一次进入食在南哪线',
    category: 'food',
    rarity: 'common',
    points: 10,
    hidden: false,
    icon: '🍜',
  },
  {
    id: 'food_02',
    name: '铁胃',
    description: '单局在食堂线连续 3 个非负面效果',
    category: 'food',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🍜',
  },
  {
    id: 'food_03',
    name: '麦门信徒',
    description: '单局中使用麦门护盾成功挡住负面效果',
    category: 'food',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🍜',
  },
  {
    id: 'food_04',
    name: '美食评论家',
    description: '累积在食堂线触发 ≥ 30 个不同格子事件',
    category: 'food',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🍜',
    maxProgress: 30,
    progressLabel: '已触发 {n}/{max} 个不同格子事件',
  },
  {
    id: 'food_05',
    name: '食堂全席',
    description: '单局走完食堂线全部格子',
    category: 'food',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🍜',
  },
  {
    id: 'food_06',
    name: '百毒不侵',
    description: '单局食堂线全程零负面',
    category: 'food',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '🍜',
  },

  // ── Chapter 10: Composite (8) ────────────────────────────────────────────
  {
    id: 'comp_01',
    name: '均衡发展',
    description: '单局 GPA ≥ 3.0 且金钱 ≥ 3000 且探索 ≥ 8',
    category: 'composite',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🏆',
  },
  {
    id: 'comp_02',
    name: '完美毕业',
    description: '单局 GPA ≥ 3.8 且金钱 ≥ 4000 且探索 ≥ 12',
    category: 'composite',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🏆',
  },
  {
    id: 'comp_03',
    name: '人生赢家',
    description: '单局 GPA ≥ 4.0 且金钱 ≥ 5000 且探索 ≥ 18',
    category: 'composite',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '🏆',
  },
  {
    id: 'comp_04',
    name: '速通大师',
    description: '在第 12 回合前就获胜',
    category: 'composite',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🏆',
  },
  {
    id: 'comp_05',
    name: '大一就毕业',
    description: '在第 6 回合前就获胜',
    category: 'composite',
    rarity: 'legendary',
    points: 100,
    hidden: false,
    icon: '🏆',
  },
  {
    id: 'comp_06',
    name: '综合分之王',
    description: '单局综合分 ≥ 70',
    category: 'composite',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🏆',
  },
  {
    id: 'comp_07',
    name: '碾压式胜利',
    description: '获胜且综合分领先第二名 ≥ 15',
    category: 'composite',
    rarity: 'epic',
    points: 50,
    hidden: false,
    icon: '🏆',
  },
  {
    id: 'comp_08',
    name: '险胜',
    description: '获胜且综合分仅领先第二名 < 3',
    category: 'composite',
    rarity: 'rare',
    points: 25,
    hidden: false,
    icon: '🏆',
  },

  // ── Chapter 11: Hidden (12) ──────────────────────────────────────────────
  {
    id: 'hidden_01',
    name: '嚼得菜根',
    description: '达成条件: 隐藏',
    revealedDescription: '嚼得菜根 — 单局结束时金钱恰好为 0',
    category: 'hidden',
    rarity: 'rare',
    points: 25,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_02',
    name: '百二十年',
    description: '达成条件: 隐藏',
    revealedDescription: '百二十年 — 单局总分恰好为 60.0',
    category: 'hidden',
    rarity: 'rare',
    points: 25,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_03',
    name: '二进制人生',
    description: '达成条件: 隐藏',
    revealedDescription: '二进制人生 — 使用计算机系且金钱和探索都只含 0 和 1',
    category: 'hidden',
    rarity: 'legendary',
    points: 100,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_04',
    name: '监狱风云',
    description: '达成条件: 隐藏',
    revealedDescription: '监狱风云 — 单局进入校医院 ≥ 5 次',
    category: 'hidden',
    rarity: 'epic',
    points: 50,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_05',
    name: '散尽家财',
    description: '达成条件: 隐藏',
    revealedDescription: '散尽家财 — 在满员局南哪诚品给 5 个玩家各发一次钱',
    category: 'hidden',
    rarity: 'epic',
    points: 50,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_06',
    name: '候车厅常客',
    description: '达成条件: 隐藏',
    revealedDescription: '候车厅常客 — 单局使用候车厅传送 ≥ 3 次',
    category: 'hidden',
    rarity: 'epic',
    points: 50,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_07',
    name: '七七七',
    description: '达成条件: 隐藏',
    revealedDescription: '七七七 — 单局结束金钱尾数为 7 且探索值含 7',
    category: 'hidden',
    rarity: 'epic',
    points: 50,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_08',
    name: '反转大师',
    description: '达成条件: 隐藏',
    revealedDescription: '反转大师 — 单局中触发风水轮转后在反转顺序中获益',
    category: 'hidden',
    rarity: 'rare',
    points: 25,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_09',
    name: '真·非酋',
    description: '达成条件: 隐藏',
    revealedDescription: '真·非酋 — 单局连续 5 次掷骰 ≤ 2',
    category: 'hidden',
    rarity: 'rare',
    points: 25,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_10',
    name: '孤注一掷',
    description: '达成条件: 隐藏',
    revealedDescription: '孤注一掷 — 使用延迟满足卡后最终获胜',
    category: 'hidden',
    rarity: 'epic',
    points: 50,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_11',
    name: '开局即巅峰',
    description: '达成条件: 隐藏',
    revealedDescription: '开局即巅峰 — 大一结束综合分全场最高但最终未获胜',
    category: 'hidden',
    rarity: 'rare',
    points: 25,
    hidden: true,
    icon: '🔮',
  },
  {
    id: 'hidden_12',
    name: '谢谢惠顾×3',
    description: '达成条件: 隐藏',
    revealedDescription: '谢谢惠顾×3 — 单局连续抽到 3 张再抽一次类效果',
    category: 'hidden',
    rarity: 'epic',
    points: 50,
    hidden: true,
    icon: '🔮',
  },
];

// ─── Helper Functions ────────────────────────────────────────────────────────

export function getAchievementById(id: string): AchievementDef | undefined {
  return ACHIEVEMENTS.find((a) => a.id === id);
}

export function getAchievementsByCategory(
  category: AchievementCategory,
): AchievementDef[] {
  return ACHIEVEMENTS.filter((a) => a.category === category);
}
